replicaCount: 1

image:
  repository: yourdockerhubusername/flask-log-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  mountPath: /var/log/flaskapp
