stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building the Python app..."
    - pip install -r requirements.txt

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - pytest
