apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-to-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: flask-log-app
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 5000
