---
- name: Configure Apache
  hosts: webservers
  become: yes
  vars:
    apache_version: "2.4"
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
      notify: Restart Apache
  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
  
  
