apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-secret-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-container
        image: nginx
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: API_KEY
        ports:
        - containerPort: 80
